#!/bin/bash
WORKSPACE=~/workspace
LINK=$WORKSPACE/ansible
ANS1404=$WORKSPACE/ansible_1404
ANS1804=$WORKSPACE/ansible_1804

if [ "$(readlink -- "$LINK")" = $ANS1404/ ]; then
    echo "using 14.04"
elif [ "$(readlink -- "$LINK")" = $ANS1804/ ]; then
    echo "using 18.04"
fi

